name: Solution Build

on:
  workflow_dispatch:
  push:
    branches: 
        - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0
          
      - name: Restore Dependencies
        run: dotnet restore src/Wachhund.sln

      - name: Release Build
        run: dotnet build src/Wachhund.sln --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test src/Wachhund.sln --configuration Release --no-restore --no-build